### ISSUE TITLE
segfault when closing window, for which MenuWidgetAny was used

### ISSUE THREAD

**Issue by nick87720z** [rilian-la-te/vala-panel-appmenu#163]
First noticed in my fork, staying in PR, but it also happens at this commit:
534d2ee4e894ac971388c95494e10408559612dd

this backtrace is for mentioned commit
https://gist.github.com/nick87720z/37caa413295a6502859185f54e3df3a9

Reproducing: open xterm, rxvt, st, any other x11 tool, then close.
It may happen not after just one attempt - several windows may be closed, not causing crash.

**Comment by rilian-la-te** [comment]
For master?

**Comment by nick87720z** [comment]
Yes, with master too - i just again tried it with version, ending with movement to Gtk.Paned.
For other, than vala, panels it is not fatal of course)
first time - silent restart, futher - asks each time

**Comment by rilian-la-te** [comment]
Will try it with xterm ASAP. If confirm - will fix.

**Comment by nick87720z** [comment]
It seems to affect any window, that doesn't provide dbusmenu of any form. When i start backintime qt5, first window, that i get, is error message. Same with qt5ct.

**Comment by rilian-la-te** [comment]
fixed AFAIK (tested with xev and xterm).

**Comment by nick87720z** [comment]
Still happens (i rebuilt both vala-panel and appmenu applet from latest upstream state)
https://gist.github.com/nick87720z/e8843e61a5c3f2b12226189a9b20fb86

Action **Close this window** works, but doesn't save from this bug

**Comment by rilian-la-te** [comment]
Provided complete steps to reproduce, please.

**Comment by rilian-la-te** [comment]
And fix your fontconfig.

**Comment by nick87720z** [comment]
Something changed, at least today is first time, i tried this case, noticing new rule.
- Start several instances of different non-gtk apps without dbus menu (xfrun4 and sakuta term don't cause such problem). For example: 3 x xterm, 3 x st (simple term, xterm-based), 3 x xev, 3 x rxvt (or whatever).
- Now try to close. For me appmenu applet survives, when switches to window of same app, as closed one. I.e., closing xterm, it switches to another one. But if you close xterm and it switches to something else - st, xev, rxvt, some gtk/qt/java app - applet will crash.
That's all.

**Comment by rilian-la-te** [comment]
Will try it.

**Comment by rilian-la-te** [comment]
Tested with 3 xev and 3 xclock - applet survives all xev-xclock jumping.

**Comment by nick87720z** [comment]
Did you have xclock focused? I don't see  any focus word in xclock man, so probably there was not swich. Or was it?

**Comment by rilian-la-te** [comment]
AFAIK, it was focused by Marco. Won`t have xfwm4 for testing:-(

**Comment by nick87720z** [comment]
I still have marco since some time (when i used compiz-reloaded), so tried with it. It is more complex. When i tried multiple xev - it crushes after each instance is closed, even if next window is also xev. With xclock - it survived 3 or 4 closed instances, crashing after next one.
I can't understand, what exactly causes it to not crash :/
`xterm & xterm & xterm & xterm & xterm & xterm & xterm & xterm & xterm & xterm & xterm & xterm & xterm & xterm & xterm & xterm & xterm & xterm & xterm & xterm & xterm & xterm & xterm & xterm & ` )

**Comment by rilian-la-te** [comment]
For me, xev does not cause a crash. Do you fixed fontconfig?

**Comment by nick87720z** [comment]
It is very hard to reproduce. Last time, running marco, i started pack of windows with this command:
`$ xterm & st & xterm & st & xterm & st & xterm & st & xterm & st & xterm & st & xterm & st & xterm & st & xterm & st & xterm & st & xterm & st & xterm & st & xterm & st & xterm & st & xterm & st &`
They did not appear in exactly same order, but still i get several app switch, while closed. It crashed only when i closed all of them, and it switched to xfce4-terminal.

**Comment by nick87720z** [comment]
My libs: gtk+-3.22.19, glib-2.50.3, glibc-2.25, gcc 6.4.0 (stabilized in gentoo upstream).

**Comment by nick87720z** [comment]
Btw, what did you mean by fontconfig fix - different fonts? I have indeed different fonts for gtk2 and gtk3. By some reason xfce font settings don't apply gtk2, need to be manually written to gtkrc.

**Comment by rilian-la-te** [comment]
You have an error in fontconfig in backtrace. You should fix it, it can be source of bug

**Comment by nick87720z** [comment]
This fontconfig error appears for everything, using fontconfig, in very startup, not when something happens. I guess, it just means, that in certain case fonts may be different. Is not it?

I just don't see any relation between object finalization in bamf (leading to gtk-widget-destroy) and this error. If applet does all ok, then it might be in bamf as well, though.

**Comment by rilian-la-te** [comment]
Try bamf from git.

**Comment by nick87720z** [comment]
It is in launchpad bzr. After rebuilding against it, applet still crashes. Btw, still not submited more completed backtrace.
https://gist.github.com/nick87720z/6ab5b06603d58a14618a39d697978b77

**Comment by rilian-la-te** [comment]
I think this is BAMF bug. But you can try with newer glib (2.52 at least) and newer Vala. It seems something wrong in vala dbus generator.
